Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
n = 5           # specify the dimension of V(n, q)
q = 2           # specify the order of GF(q)
space = v(n, q) # construct V(n, q) over GF(q)

print('V(' + str(n) + ', ' + str(q) + ')')
print()
print('{}\t{}\t{}'.format(str(n**q) + ' vectors', 'weight', str(q) + ' scalar multiples per vector'))
print()
for i, vector in enumerate(space):
    print('{}\t{}\t{}\t{}'.format(i, vector, vector_weight(vector), generate_scalar_multiples(vector, q)))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-7-4b586a4cb152>[0m in [0;36m<module>[0;34m[0m
[1;32m      8[0m [0mprint[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      9[0m [0;32mfor[0m [0mi[0m[0;34m,[0m [0mvector[0m [0;32min[0m [0menumerate[0m[0;34m([0m[0mspace[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 10[0;31m     [0mprint[0m[0;34m([0m[0;34m'{}\t{}\t{}\t{}'[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mi[0m[0;34m,[0m [0mvector[0m[0;34m,[0m [0mvector_weight[0m[0;34m([0m[0mvector[0m[0;34m)[0m[0;34m,[0m [0mgenerate_scalar_multiples[0m[0;34m([0m[0mvector[0m[0;34m,[0m [0mq[0m[0;34m)[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'vector_weight' is not defined
NameError: name 'vector_weight' is not defined

